/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC.h"

bool_t
xdr_input (XDR *xdrs, input *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->pass, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->command, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_output (XDR *xdrs, output *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->result, ~0))
		 return FALSE;
	return TRUE;
}
